
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu May 04 14:03:32 EDT 2017
//----------------------------------------------------

package bantam.parser;

import bantam.lexer.*;
import bantam.mast.*;
import bantam.util.ErrorHandler;
import java_cup.runtime.Symbol;

/** CUP v0.10k generated parser.
  * @version Thu May 04 14:03:32 EDT 2017
  */
public class Parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\101\000\002\003\003\000\002\002\004\000\002\004" +
    "\011\000\002\004\007\000\002\005\003\000\002\005\004" +
    "\000\002\005\002\000\002\006\003\000\002\006\003\000" +
    "\002\007\006\000\002\011\003\000\002\011\003\000\002" +
    "\011\003\000\002\011\003\000\002\014\004\000\002\012" +
    "\007\000\002\015\006\000\002\010\003\000\002\010\004" +
    "\000\002\010\002\000\002\025\003\000\002\025\003\000" +
    "\002\024\003\000\002\024\005\000\002\024\002\000\002" +
    "\027\003\000\002\027\005\000\002\027\007\000\002\027" +
    "\011\000\002\027\007\000\002\027\011\000\002\027\005" +
    "\000\002\027\007\000\002\027\011\000\002\027\007\000" +
    "\002\027\011\000\002\027\005\000\002\027\007\000\002" +
    "\027\011\000\002\027\007\000\002\027\011\000\002\016" +
    "\003\000\002\016\004\000\002\016\002\000\002\017\005" +
    "\000\002\020\003\000\002\020\004\000\002\020\002\000" +
    "\002\021\003\000\002\021\003\000\002\022\005\000\002" +
    "\023\005\000\002\023\006\000\002\023\006\000\002\023" +
    "\003\000\002\023\004\000\002\023\004\000\002\026\003" +
    "\000\002\026\003\000\002\026\003\000\002\032\003\000" +
    "\002\030\003\000\002\030\004\000\002\030\004\000\002" +
    "\031\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\171\000\004\005\006\001\002\000\004\002\173\001" +
    "\002\000\004\002\001\001\002\000\004\032\007\001\002" +
    "\000\006\017\010\025\011\001\002\000\034\006\040\007" +
    "\015\010\023\011\027\012\024\013\012\020\ufffb\021\042" +
    "\023\020\026\ufffb\030\025\031\014\032\017\001\002\000" +
    "\026\007\015\010\023\011\027\012\024\013\012\017\uffd6" +
    "\023\020\030\025\031\014\032\017\001\002\000\004\031" +
    "\170\001\002\000\014\017\uffd8\022\uffd8\023\uffd8\026\uffd8" +
    "\027\uffd8\001\002\000\032\007\uffc4\010\uffc4\011\uffc4\015" +
    "\uffc4\016\uffc4\017\uffc4\022\uffc4\023\uffc4\024\uffc4\026\uffc4" +
    "\027\uffc4\033\uffc4\001\002\000\014\012\024\013\012\030" +
    "\025\031\014\032\017\001\002\000\012\017\uffed\022\uffed" +
    "\026\uffed\027\uffed\001\002\000\032\007\uffc1\010\uffc1\011" +
    "\uffc1\015\uffc1\016\uffc1\017\uffc1\022\uffc1\023\uffc1\024\uffc1" +
    "\026\uffc1\027\uffc1\033\uffc1\001\002\000\010\015\132\024" +
    "\uffd2\033\135\001\002\000\012\017\uffec\022\uffec\026\uffec" +
    "\027\uffec\001\002\000\032\007\uffc8\010\uffc8\011\uffc8\015" +
    "\uffc8\016\uffc8\017\uffc8\022\uffc8\023\uffc8\024\uffc8\026\uffc8" +
    "\027\uffc8\033\uffc8\001\002\000\014\012\024\013\012\030" +
    "\025\031\014\032\017\001\002\000\004\031\111\001\002" +
    "\000\034\007\uffc5\010\uffc5\011\uffc5\014\uffc5\015\uffc5\016" +
    "\uffc5\017\uffc5\022\uffc5\023\uffc5\024\uffc5\026\uffc5\027\uffc5" +
    "\033\uffc5\001\002\000\014\017\uffe8\022\uffe8\023\020\026" +
    "\uffe8\027\uffe8\001\002\000\014\012\024\013\012\030\025" +
    "\031\014\032\017\001\002\000\004\017\033\001\002\000" +
    "\032\007\uffc6\010\uffc6\011\uffc6\015\uffc6\016\uffc6\017\uffc6" +
    "\022\uffc6\023\uffc6\024\uffc6\026\uffc6\027\uffc6\033\uffc6\001" +
    "\002\000\032\007\uffc7\010\uffc7\011\uffc7\015\uffc7\016\uffc7" +
    "\017\uffc7\022\uffc7\023\uffc7\024\uffc7\026\uffc7\027\uffc7\033" +
    "\uffc7\001\002\000\034\006\040\007\015\010\023\011\027" +
    "\012\024\013\012\020\ufffb\021\042\023\020\026\ufffb\030" +
    "\025\031\014\032\017\001\002\000\034\006\040\007\015" +
    "\010\023\011\027\012\024\013\012\020\071\021\042\023" +
    "\020\026\uffd6\030\025\031\014\032\017\001\002\000\034" +
    "\006\ufffd\007\ufffd\010\ufffd\011\ufffd\012\ufffd\013\ufffd\020" +
    "\ufffd\021\ufffd\023\ufffd\026\ufffd\030\ufffd\031\ufffd\032\ufffd" +
    "\001\002\000\034\006\ufffa\007\ufffa\010\ufffa\011\ufffa\012" +
    "\ufffa\013\ufffa\020\ufffa\021\ufffa\023\ufffa\026\ufffa\030\ufffa" +
    "\031\ufffa\032\ufffa\001\002\000\004\026\067\001\002\000" +
    "\026\007\015\010\023\011\027\012\024\013\012\017\uffd6" +
    "\023\020\030\025\031\014\032\017\001\002\000\034\006" +
    "\ufff7\007\ufff7\010\ufff7\011\ufff7\012\ufff7\013\ufff7\020\ufff7" +
    "\021\ufff7\023\ufff7\026\ufff7\030\ufff7\031\ufff7\032\ufff7\001" +
    "\002\000\030\007\015\010\023\011\027\012\024\013\012" +
    "\022\uffe9\023\020\027\uffe9\030\025\031\014\032\017\001" +
    "\002\000\006\014\050\026\uffc7\001\002\000\034\006\ufff4" +
    "\007\ufff4\010\ufff4\011\ufff4\012\ufff4\013\ufff4\020\ufff4\021" +
    "\ufff4\023\ufff4\026\ufff4\030\ufff4\031\ufff4\032\ufff4\001\002" +
    "\000\034\006\ufff6\007\ufff6\010\ufff6\011\ufff6\012\ufff6\013" +
    "\ufff6\020\ufff6\021\ufff6\023\ufff6\026\ufff6\030\ufff6\031\ufff6" +
    "\032\ufff6\001\002\000\034\006\ufff5\007\ufff5\010\ufff5\011" +
    "\ufff5\012\ufff5\013\ufff5\020\ufff5\021\ufff5\023\ufff5\026\ufff5" +
    "\030\ufff5\031\ufff5\032\ufff5\001\002\000\034\006\ufff9\007" +
    "\ufff9\010\ufff9\011\ufff9\012\ufff9\013\ufff9\020\ufff9\021\ufff9" +
    "\023\ufff9\026\ufff9\030\ufff9\031\ufff9\032\ufff9\001\002\000" +
    "\026\007\015\010\023\011\027\012\024\013\012\023\020" +
    "\026\uffd6\030\025\031\014\032\017\001\002\000\004\026" +
    "\052\001\002\000\034\006\ufff8\007\ufff8\010\ufff8\011\ufff8" +
    "\012\ufff8\013\ufff8\020\ufff8\021\ufff8\023\ufff8\026\ufff8\030" +
    "\ufff8\031\ufff8\032\ufff8\001\002\000\006\022\uffeb\027\uffeb" +
    "\001\002\000\006\022\055\027\056\001\002\000\004\026" +
    "\060\001\002\000\030\007\015\010\023\011\027\012\024" +
    "\013\012\022\uffd6\023\020\027\uffd6\030\025\031\014\032" +
    "\017\001\002\000\006\022\uffea\027\uffea\001\002\000\034" +
    "\006\ufff1\007\ufff1\010\ufff1\011\ufff1\012\ufff1\013\ufff1\020" +
    "\ufff1\021\ufff1\023\ufff1\026\ufff1\030\ufff1\031\ufff1\032\ufff1" +
    "\001\002\000\004\017\062\001\002\000\034\006\040\007" +
    "\015\010\023\011\027\012\024\013\012\020\uffee\021\042" +
    "\023\020\026\uffee\030\025\031\014\032\017\001\002\000" +
    "\034\006\040\007\015\010\023\011\027\012\024\013\012" +
    "\020\065\021\042\023\020\026\uffd6\030\025\031\014\032" +
    "\017\001\002\000\034\006\ufff0\007\ufff0\010\ufff0\011\ufff0" +
    "\012\ufff0\013\ufff0\020\ufff0\021\ufff0\023\ufff0\026\ufff0\030" +
    "\ufff0\031\ufff0\032\ufff0\001\002\000\034\006\ufff2\007\ufff2" +
    "\010\ufff2\011\ufff2\012\ufff2\013\ufff2\020\ufff2\021\ufff2\023" +
    "\ufff2\026\ufff2\030\ufff2\031\ufff2\032\ufff2\001\002\000\034" +
    "\006\uffef\007\uffef\010\uffef\011\uffef\012\uffef\013\uffef\020" +
    "\uffef\021\uffef\023\uffef\026\uffef\030\uffef\031\uffef\032\uffef" +
    "\001\002\000\034\006\ufff3\007\ufff3\010\ufff3\011\ufff3\012" +
    "\ufff3\013\ufff3\020\ufff3\021\ufff3\023\ufff3\026\ufff3\030\ufff3" +
    "\031\ufff3\032\ufff3\001\002\000\034\006\ufffc\007\ufffc\010" +
    "\ufffc\011\ufffc\012\ufffc\013\ufffc\020\ufffc\021\ufffc\023\ufffc" +
    "\026\ufffc\030\ufffc\031\ufffc\032\ufffc\001\002\000\004\002" +
    "\uffff\001\002\000\020\007\075\010\074\017\uffd6\022\uffd6" +
    "\023\020\026\uffd6\027\uffd6\001\002\000\014\017\uffe2\022" +
    "\uffe2\023\020\026\uffe2\027\uffe2\001\002\000\014\012\024" +
    "\013\012\030\025\031\014\032\017\001\002\000\014\012" +
    "\024\013\012\030\025\031\014\032\017\001\002\000\016" +
    "\010\100\017\uffd6\022\uffd6\023\020\026\uffd6\027\uffd6\001" +
    "\002\000\014\017\uffe1\022\uffe1\023\020\026\uffe1\027\uffe1" +
    "\001\002\000\014\012\024\013\012\030\025\031\014\032" +
    "\017\001\002\000\014\017\uffd6\022\uffd6\023\020\026\uffd6" +
    "\027\uffd6\001\002\000\014\017\uffe0\022\uffe0\023\020\026" +
    "\uffe0\027\uffe0\001\002\000\014\017\uffd7\022\uffd7\023\uffd7" +
    "\026\uffd7\027\uffd7\001\002\000\016\007\106\017\uffd6\022" +
    "\uffd6\023\020\026\uffd6\027\uffd6\001\002\000\014\017\uffdf" +
    "\022\uffdf\023\020\026\uffdf\027\uffdf\001\002\000\014\012" +
    "\024\013\012\030\025\031\014\032\017\001\002\000\014" +
    "\017\uffd6\022\uffd6\023\020\026\uffd6\027\uffd6\001\002\000" +
    "\014\017\uffde\022\uffde\023\020\026\uffde\027\uffde\001\002" +
    "\000\032\007\uffc2\010\uffc2\011\uffc2\015\uffc2\016\uffc2\017" +
    "\uffc2\022\uffc2\023\uffc2\024\uffc2\026\uffc2\027\uffc2\033\uffc2" +
    "\001\002\000\020\007\115\011\114\017\uffd6\022\uffd6\023" +
    "\020\026\uffd6\027\uffd6\001\002\000\014\017\uffdd\022\uffdd" +
    "\023\020\026\uffdd\027\uffdd\001\002\000\014\012\024\013" +
    "\012\030\025\031\014\032\017\001\002\000\014\012\024" +
    "\013\012\030\025\031\014\032\017\001\002\000\016\011" +
    "\120\017\uffd6\022\uffd6\023\020\026\uffd6\027\uffd6\001\002" +
    "\000\014\017\uffdc\022\uffdc\023\020\026\uffdc\027\uffdc\001" +
    "\002\000\014\012\024\013\012\030\025\031\014\032\017" +
    "\001\002\000\014\017\uffd6\022\uffd6\023\020\026\uffd6\027" +
    "\uffd6\001\002\000\014\017\uffdb\022\uffdb\023\020\026\uffdb" +
    "\027\uffdb\001\002\000\016\007\125\017\uffd6\022\uffd6\023" +
    "\020\026\uffd6\027\uffd6\001\002\000\014\017\uffda\022\uffda" +
    "\023\020\026\uffda\027\uffda\001\002\000\014\012\024\013" +
    "\012\030\025\031\014\032\017\001\002\000\014\017\uffd6" +
    "\022\uffd6\023\020\026\uffd6\027\uffd6\001\002\000\014\017" +
    "\uffd9\022\uffd9\023\020\026\uffd9\027\uffd9\001\002\000\010" +
    "\015\132\024\151\033\135\001\002\000\012\015\uffd0\016" +
    "\uffd0\024\uffd0\033\uffd0\001\002\000\010\015\132\016\uffd2" +
    "\033\135\001\002\000\012\015\uffd4\016\uffd4\024\uffd4\033" +
    "\uffd4\001\002\000\012\015\uffd1\016\uffd1\024\uffd1\033\uffd1" +
    "\001\002\000\020\012\136\013\140\015\uffcb\016\uffcb\024" +
    "\uffcb\025\137\033\uffcb\001\002\000\014\015\uffca\016\uffca" +
    "\024\uffca\025\144\033\uffca\001\002\000\014\012\024\013" +
    "\012\030\025\031\014\032\017\001\002\000\014\015\uffc9" +
    "\016\uffc9\024\uffc9\025\141\033\uffc9\001\002\000\014\012" +
    "\024\013\012\030\025\031\014\032\017\001\002\000\012" +
    "\015\uffcc\016\uffcc\024\uffcc\033\uffcc\001\002\000\012\015" +
    "\uffce\016\uffce\024\uffce\033\uffce\001\002\000\014\012\024" +
    "\013\012\030\025\031\014\032\017\001\002\000\012\015" +
    "\uffcd\016\uffcd\024\uffcd\033\uffcd\001\002\000\010\015\132" +
    "\016\147\033\135\001\002\000\012\015\uffcf\016\uffcf\024" +
    "\uffcf\033\uffcf\001\002\000\012\015\uffd3\016\uffd3\024\uffd3" +
    "\033\uffd3\001\002\000\014\017\uffd5\022\uffd5\023\uffd5\026" +
    "\uffd5\027\uffd5\001\002\000\020\010\155\011\154\017\uffd6" +
    "\022\uffd6\023\020\026\uffd6\027\uffd6\001\002\000\014\017" +
    "\uffe7\022\uffe7\023\020\026\uffe7\027\uffe7\001\002\000\014" +
    "\012\024\013\012\030\025\031\014\032\017\001\002\000" +
    "\014\012\024\013\012\030\025\031\014\032\017\001\002" +
    "\000\016\011\160\017\uffd6\022\uffd6\023\020\026\uffd6\027" +
    "\uffd6\001\002\000\014\017\uffe4\022\uffe4\023\020\026\uffe4" +
    "\027\uffe4\001\002\000\014\012\024\013\012\030\025\031" +
    "\014\032\017\001\002\000\014\017\uffd6\022\uffd6\023\020" +
    "\026\uffd6\027\uffd6\001\002\000\014\017\uffe3\022\uffe3\023" +
    "\020\026\uffe3\027\uffe3\001\002\000\016\010\165\017\uffd6" +
    "\022\uffd6\023\020\026\uffd6\027\uffd6\001\002\000\014\017" +
    "\uffe6\022\uffe6\023\020\026\uffe6\027\uffe6\001\002\000\014" +
    "\012\024\013\012\030\025\031\014\032\017\001\002\000" +
    "\014\017\uffd6\022\uffd6\023\020\026\uffd6\027\uffd6\001\002" +
    "\000\014\017\uffe5\022\uffe5\023\020\026\uffe5\027\uffe5\001" +
    "\002\000\032\007\uffc3\010\uffc3\011\uffc3\015\uffc3\016\uffc3" +
    "\017\uffc3\022\uffc3\023\uffc3\024\uffc3\026\uffc3\027\uffc3\033" +
    "\uffc3\001\002\000\034\006\040\007\015\010\023\011\027" +
    "\012\024\013\012\020\172\021\042\023\020\026\uffd6\030" +
    "\025\031\014\032\017\001\002\000\004\002\ufffe\001\002" +
    "\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\171\000\006\003\003\004\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\042\005\170\006\034\007\035\011\046\012\040\013" +
    "\044\014\045\015\043\016\025\017\012\025\036\026\020" +
    "\027\015\030\021\031\030\032\042\001\001\000\022\016" +
    "\025\017\012\025\027\026\020\027\015\030\021\031\030" +
    "\032\031\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\026\151\030\021\031\030\032\031" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\020" +
    "\127\021\132\022\133\023\130\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\026\111\030\021\031\030\032" +
    "\031\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\017\102\001\001\000\012\026\071\030\021\031\030\032" +
    "\031\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\042\005\033\006\034\007\035\011\046\012" +
    "\040\013\044\014\045\015\043\016\025\017\012\025\036" +
    "\026\020\027\015\030\021\031\030\032\042\001\001\000" +
    "\040\006\067\007\035\011\046\012\040\013\044\014\045" +
    "\015\043\016\025\017\012\025\036\026\020\027\015\030" +
    "\021\031\030\032\042\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\022\016\025\017\012\025" +
    "\060\026\020\027\015\030\021\031\030\032\031\001\001" +
    "\000\002\001\001\000\024\016\025\017\012\024\053\025" +
    "\052\026\020\027\015\030\021\031\030\032\031\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\022\016\025\017\012" +
    "\025\050\026\020\027\015\030\021\031\030\032\031\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\016\025\017" +
    "\012\025\056\026\020\027\015\030\021\031\030\032\031" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\036\010\062\011\063\012\040\013\044\014\045" +
    "\015\043\016\025\017\012\025\036\026\020\027\015\030" +
    "\021\031\030\032\031\001\001\000\034\011\065\012\040" +
    "\013\044\014\045\015\043\016\025\017\012\025\036\026" +
    "\020\027\015\030\021\031\030\032\031\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\016\072" +
    "\017\012\001\001\000\004\017\102\001\001\000\012\026" +
    "\103\030\021\031\030\032\031\001\001\000\012\026\075" +
    "\030\021\031\030\032\031\001\001\000\006\016\076\017" +
    "\012\001\001\000\004\017\102\001\001\000\012\026\100" +
    "\030\021\031\030\032\031\001\001\000\006\016\101\017" +
    "\012\001\001\000\004\017\102\001\001\000\002\001\001" +
    "\000\006\016\104\017\012\001\001\000\004\017\102\001" +
    "\001\000\012\026\106\030\021\031\030\032\031\001\001" +
    "\000\006\016\107\017\012\001\001\000\004\017\102\001" +
    "\001\000\002\001\001\000\006\016\112\017\012\001\001" +
    "\000\004\017\102\001\001\000\012\026\122\030\021\031" +
    "\030\032\031\001\001\000\012\026\115\030\021\031\030" +
    "\032\031\001\001\000\006\016\116\017\012\001\001\000" +
    "\004\017\102\001\001\000\012\026\120\030\021\031\030" +
    "\032\031\001\001\000\006\016\121\017\012\001\001\000" +
    "\004\017\102\001\001\000\006\016\123\017\012\001\001" +
    "\000\004\017\102\001\001\000\012\026\125\030\021\031" +
    "\030\032\031\001\001\000\006\016\126\017\012\001\001" +
    "\000\004\017\102\001\001\000\010\021\147\022\133\023" +
    "\130\001\001\000\002\001\001\000\012\020\145\021\132" +
    "\022\133\023\130\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\026\142" +
    "\030\021\031\030\032\031\001\001\000\002\001\001\000" +
    "\012\026\141\030\021\031\030\032\031\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\026\144\030\021\031" +
    "\030\032\031\001\001\000\002\001\001\000\010\021\147" +
    "\022\133\023\130\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\016\152\017\012\001\001" +
    "\000\004\017\102\001\001\000\012\026\162\030\021\031" +
    "\030\032\031\001\001\000\012\026\155\030\021\031\030" +
    "\032\031\001\001\000\006\016\156\017\012\001\001\000" +
    "\004\017\102\001\001\000\012\026\160\030\021\031\030" +
    "\032\031\001\001\000\006\016\161\017\012\001\001\000" +
    "\004\017\102\001\001\000\006\016\163\017\012\001\001" +
    "\000\004\017\102\001\001\000\012\026\165\030\021\031" +
    "\030\032\031\001\001\000\006\016\166\017\012\001\001" +
    "\000\004\017\102\001\001\000\002\001\001\000\040\006" +
    "\067\007\035\011\046\012\040\013\044\014\045\015\043" +
    "\016\025\017\012\025\036\026\020\027\015\030\021\031" +
    "\030\032\042\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    /**
     * @return the ErrorHandler for this Parser
     */
    public ErrorHandler getErrorHandler() { return action_obj.getErrorHandler(); }

    /** overrides done_parsing in inherited class, called when parsing finishes
      * either after accepting or because of errors
      * */
    public void done_parsing() {
	super.done_parsing();
	// if lexing and/or parsing errors then exit
	action_obj.getErrorHandler().checkErrors();
    }

    /**
     * Generates an appropriate error message based on the
     * input error type
     * @param t the relevant error Token
     */
    private String generateErrorMessage(Token t) {
        String errorMessage = "";
        switch(t.getName()) {
            case "UNTERMINATED_COMMENT":
                errorMessage = "unterminated comment detected";
            case "LARGE_INT":
                errorMessage = (
                    "int value " + t.getAttribute() + "is too large. Bantam Java only " +
                    "supports integers of size 2147483647 (2^32 - 1) or less"
                );
            case "ILLEGAL_ID":
                errorMessage = "illegal id '" + t.getAttribute() + "'";
            case "LARGE_STRING":
                errorMessage = (
                    "Bantam Java Strings cannot exceed 5000 chars." +
                    "Found string of size: " + t.getAttribute()
                );
            case "ILLEGAL_ESCAPE_CHAR":
                errorMessage = "illegal escape char: '" + t.getAttribute() + "'";
            case "MULTILINE_STRING":
                errorMessage = "multiline string detected";
            case "UNTERMINATED_STRING":
                errorMessage = "unterminated string: '" + t.getAttribute() + "'";
            case "ILLEGAL_CHAR":
                errorMessage = "illegal char: '" + t.getAttribute() + "'";
        }
        return errorMessage;
    }

    /** overrides syntax_error in inherited class and handles syntax errors 
      * @param curr current symbol from the bantam.lexer
      * */
    public void syntax_error(Symbol curr) {
	// get token value from the symbol
	Token t = (Token)curr.value;
	
	// get the error handler object
	ErrorHandler errorHandler = action_obj.getErrorHandler();

	// may want to modify and augment the code below for more
	// accurate error reporting
	errorHandler.register(errorHandler.PARSE_ERROR, action_obj.getCurrFilename(), 
			      action_obj.getCurrLineNum(), 
			      "unexpected input near '" + t.getLexeme() + "'");

    // handle lexer errors
    // TODO figure out why "EOF" is detected as a LEX_ERROR whenever any error occurs
    if(t.getName() != "EOF") {
        errorHandler.register(errorHandler.LEX_ERROR, action_obj.getCurrFilename(),
    			      action_obj.getCurrLineNum(),
    			      generateErrorMessage(t));
        }
    }

    /** override error_sync_size in inherited class and
      * change the minimum number of tokens to skip on an error from 3 to 2
      * @return minimum number of tokens to skip on an error
      * */
    protected int error_sync_size() {
	return 2;
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Parser$actions {

 
    /** object for error handling */
    private ErrorHandler errorHandler = new ErrorHandler();

    /* sets the error handler */
    public ErrorHandler getErrorHandler() {
	return errorHandler;
    }

    /* returns the current line number from the scanner */
    public int getCurrLineNum() {
	return ((Lexer)parser.getScanner()).getCurrLineNum();
    }

    /* returns the current file name from the scanner */
    public String getCurrFilename() {
	return ((Lexer)parser.getScanner()).getCurrFilename();
    }

  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // const_string ::= STRING_CONST 
            {
              ConstExpr RESULT = null;
		Token value = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new ConstStringExpr(value.getLineNum(), value.getAttribute()); 
              CUP$Parser$result = new java_cup.runtime.Symbol(23/*const_string*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // const_int ::= PLUS INT_CONST 
            {
              ConstExpr RESULT = null;
		Token p = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		Token value = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new ConstIntExpr(value.getLineNum(), "+" + value.getAttribute()); 
              CUP$Parser$result = new java_cup.runtime.Symbol(22/*const_int*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // const_int ::= MINUS INT_CONST 
            {
              ConstExpr RESULT = null;
		Token m = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		Token value = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new ConstIntExpr(value.getLineNum(), "-" + value.getAttribute()); 
              CUP$Parser$result = new java_cup.runtime.Symbol(22/*const_int*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // const_int ::= INT_CONST 
            {
              ConstExpr RESULT = null;
		Token value = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new ConstIntExpr(value.getLineNum(), value.getAttribute()); 
              CUP$Parser$result = new java_cup.runtime.Symbol(22/*const_int*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // const_var ::= ID 
            {
              ConstExpr RESULT = null;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new ConstVarExpr(
                            id.getLineNum(),
                            id.getAttribute());
        
              CUP$Parser$result = new java_cup.runtime.Symbol(24/*const_var*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // const_expr ::= const_string 
            {
              Expr RESULT = null;
		ConstExpr i = (ConstExpr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = i; 
              CUP$Parser$result = new java_cup.runtime.Symbol(20/*const_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // const_expr ::= const_var 
            {
              Expr RESULT = null;
		ConstExpr i = (ConstExpr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = i; 
              CUP$Parser$result = new java_cup.runtime.Symbol(20/*const_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // const_expr ::= const_int 
            {
              Expr RESULT = null;
		ConstExpr i = (ConstExpr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = i; 
              CUP$Parser$result = new java_cup.runtime.Symbol(20/*const_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // note ::= NOTE MINUS 
            {
              Note RESULT = null;
		Token n = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Note(n.getLineNum(), n.getAttribute(), "-"); 
              CUP$Parser$result = new java_cup.runtime.Symbol(17/*note*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // note ::= NOTE PLUS 
            {
              Note RESULT = null;
		Token n = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Note(n.getLineNum(), n.getAttribute(), "+"); 
              CUP$Parser$result = new java_cup.runtime.Symbol(17/*note*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // note ::= NOTE 
            {
              Note RESULT = null;
		Token n = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new Note(n.getLineNum(), n.getAttribute(), null); 
              CUP$Parser$result = new java_cup.runtime.Symbol(17/*note*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // note ::= NOTE MINUS BREAK const_expr 
            {
              Note RESULT = null;
		Token n = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new Note(n.getLineNum(), n.getAttribute(), "-", (ConstExpr)e); 
              CUP$Parser$result = new java_cup.runtime.Symbol(17/*note*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // note ::= NOTE PLUS BREAK const_expr 
            {
              Note RESULT = null;
		Token n = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new Note(n.getLineNum(), n.getAttribute(), "+", (ConstExpr)e); 
              CUP$Parser$result = new java_cup.runtime.Symbol(17/*note*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // note ::= NOTE BREAK const_expr 
            {
              Note RESULT = null;
		Token n = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new Note(n.getLineNum(), n.getAttribute(), null, (ConstExpr)e); 
              CUP$Parser$result = new java_cup.runtime.Symbol(17/*note*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // chord ::= LPAREN sound_list RPAREN 
            {
              Chord RESULT = null;
		SoundList sl = (SoundList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Chord(sl.getLineNum(), sl); 
              CUP$Parser$result = new java_cup.runtime.Symbol(16/*chord*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // sound ::= note 
            {
              Sound RESULT = null;
		Note n = (Note)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = n; 
              CUP$Parser$result = new java_cup.runtime.Symbol(15/*sound*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // sound ::= chord 
            {
              Sound RESULT = null;
		Chord c = (Chord)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = c; 
              CUP$Parser$result = new java_cup.runtime.Symbol(15/*sound*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // sound_list ::= 
            {
              SoundList RESULT = null;
		 RESULT = new SoundList(getCurrLineNum()); 
              CUP$Parser$result = new java_cup.runtime.Symbol(14/*sound_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // sound_list ::= sound_list sound 
            {
              SoundList RESULT = null;
		SoundList sl = (SoundList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		Sound s = (Sound)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = (SoundList)sl.addElement(s); 
              CUP$Parser$result = new java_cup.runtime.Symbol(14/*sound_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // sound_list ::= sound 
            {
              SoundList RESULT = null;
		Sound s = (Sound)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = (SoundList)(new SoundList(s.getLineNum()).addElement(s)); 
              CUP$Parser$result = new java_cup.runtime.Symbol(14/*sound_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // measure ::= LBREAK sound_list RBREAK 
            {
              Measure RESULT = null;
		SoundList sl = (SoundList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Measure(sl.getLineNum(), sl); 
              CUP$Parser$result = new java_cup.runtime.Symbol(13/*measure*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // measure_list ::= 
            {
              MeasureList RESULT = null;
		 RESULT = new MeasureList(getCurrLineNum()); 
              CUP$Parser$result = new java_cup.runtime.Symbol(12/*measure_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // measure_list ::= measure_list measure 
            {
              MeasureList RESULT = null;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		Measure m = (Measure)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = (MeasureList)ml.addElement(m); 
              CUP$Parser$result = new java_cup.runtime.Symbol(12/*measure_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // measure_list ::= measure 
            {
              MeasureList RESULT = null;
		Measure m = (Measure)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = (MeasureList)(new MeasureList(m.getLineNum()).addElement(m)); 
              CUP$Parser$result = new java_cup.runtime.Symbol(12/*measure_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // phrase_expr ::= VOLUME const_expr OCTAVE const_expr INSTRUMENT const_expr measure_list 
            {
              Expr RESULT = null;
		Expr v = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		Expr o = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr i = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), i,o,v, ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // phrase_expr ::= VOLUME const_expr OCTAVE const_expr measure_list 
            {
              Expr RESULT = null;
		Expr v = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr o = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), null,o,v, ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // phrase_expr ::= VOLUME const_expr INSTRUMENT const_expr OCTAVE const_expr measure_list 
            {
              Expr RESULT = null;
		Expr v = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		Expr i = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr o = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), i,o,v, ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // phrase_expr ::= VOLUME const_expr INSTRUMENT const_expr measure_list 
            {
              Expr RESULT = null;
		Expr v = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr i = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), i,null,v, ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // phrase_expr ::= VOLUME const_expr measure_list 
            {
              Expr RESULT = null;
		Expr v = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), null,null,v, ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // phrase_expr ::= OCTAVE const_expr VOLUME const_expr INSTRUMENT const_expr measure_list 
            {
              Expr RESULT = null;
		Expr o = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		Expr v = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr i = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), i,o,v, ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // phrase_expr ::= OCTAVE const_expr VOLUME const_expr measure_list 
            {
              Expr RESULT = null;
		Expr o = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr v = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), null,o,v, ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // phrase_expr ::= OCTAVE const_expr INSTRUMENT const_expr VOLUME const_expr measure_list 
            {
              Expr RESULT = null;
		Expr o = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		Expr i = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr v = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), i,o,v, ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // phrase_expr ::= OCTAVE const_expr INSTRUMENT const_expr measure_list 
            {
              Expr RESULT = null;
		Expr o = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr i = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), i,o,null, ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // phrase_expr ::= OCTAVE const_expr measure_list 
            {
              Expr RESULT = null;
		Expr o = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), null,o,null, ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // phrase_expr ::= INSTRUMENT const_expr VOLUME const_expr OCTAVE const_expr measure_list 
            {
              Expr RESULT = null;
		Expr i = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		Expr v = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr o = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), i,o,v, ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // phrase_expr ::= INSTRUMENT const_expr VOLUME const_expr measure_list 
            {
              Expr RESULT = null;
		Expr i = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr v = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), i,null,v, ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // phrase_expr ::= INSTRUMENT const_expr OCTAVE const_expr VOLUME const_expr measure_list 
            {
              Expr RESULT = null;
		Expr i = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		Expr o = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr v = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), i,o,v, ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // phrase_expr ::= INSTRUMENT const_expr OCTAVE const_expr measure_list 
            {
              Expr RESULT = null;
		Expr i = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr o = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), i,o,null,ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // phrase_expr ::= INSTRUMENT const_expr measure_list 
            {
              Expr RESULT = null;
		Expr i = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), i,null,null,ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // phrase_expr ::= measure_list 
            {
              Expr RESULT = null;
		MeasureList ml = (MeasureList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new PhraseExpr(ml.getLineNum(), null,null,null,ml); 
              CUP$Parser$result = new java_cup.runtime.Symbol(21/*phrase_expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expr_list ::= 
            {
              ExprList RESULT = null;
		 RESULT = new ExprList(getCurrLineNum()); 
              CUP$Parser$result = new java_cup.runtime.Symbol(18/*expr_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expr_list ::= expr_list COMMA expr 
            {
              ExprList RESULT = null;
		ExprList el = (ExprList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = (ExprList)el.addElement(e); 
              CUP$Parser$result = new java_cup.runtime.Symbol(18/*expr_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expr_list ::= expr 
            {
              ExprList RESULT = null;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = (ExprList)(new ExprList(e.getLineNum()).addElement(e)); 
              CUP$Parser$result = new java_cup.runtime.Symbol(18/*expr_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expr ::= const_expr 
            {
              Expr RESULT = null;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = e; 
              CUP$Parser$result = new java_cup.runtime.Symbol(19/*expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expr ::= phrase_expr 
            {
              Expr RESULT = null;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = e; 
              CUP$Parser$result = new java_cup.runtime.Symbol(19/*expr*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // stmt_list ::= 
            {
              StmtList RESULT = null;
		 RESULT = new StmtList(getCurrLineNum()); 
              CUP$Parser$result = new java_cup.runtime.Symbol(6/*stmt_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // stmt_list ::= stmt_list stmt 
            {
              StmtList RESULT = null;
		StmtList st = (StmtList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = (StmtList)st.addElement(s); 
              CUP$Parser$result = new java_cup.runtime.Symbol(6/*stmt_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // stmt_list ::= stmt 
            {
              StmtList RESULT = null;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = (StmtList)(new StmtList(s.getLineNum()).addElement(s)); 
              CUP$Parser$result = new java_cup.runtime.Symbol(6/*stmt_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // block_stmt ::= LSQBRACE expr_list RSQBRACE SEMI 
            {
              Stmt RESULT = null;
		ExprList sl = (ExprList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = new BlockStmt(sl.getLineNum(), sl); 
              CUP$Parser$result = new java_cup.runtime.Symbol(11/*block_stmt*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // loop_stmt ::= LOOP expr LBRACE stmt_list RBRACE 
            {
              Stmt RESULT = null;
		Expr c = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		StmtList sl = (StmtList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new LoopStmt(c.getLineNum(), sl, c); 
              CUP$Parser$result = new java_cup.runtime.Symbol(8/*loop_stmt*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // call_stmt ::= expr SEMI 
            {
              Stmt RESULT = null;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new CallStmt(e.getLineNum(), e); 
              CUP$Parser$result = new java_cup.runtime.Symbol(10/*call_stmt*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // stmt ::= block_stmt 
            {
              Stmt RESULT = null;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = s; 
              CUP$Parser$result = new java_cup.runtime.Symbol(7/*stmt*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // stmt ::= call_stmt 
            {
              Stmt RESULT = null;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = s; 
              CUP$Parser$result = new java_cup.runtime.Symbol(7/*stmt*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt ::= phrase_stmt 
            {
              Stmt RESULT = null;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = s; 
              CUP$Parser$result = new java_cup.runtime.Symbol(7/*stmt*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmt ::= loop_stmt 
            {
              Stmt RESULT = null;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = s; 
              CUP$Parser$result = new java_cup.runtime.Symbol(7/*stmt*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // field ::= const_var ASSIGN expr SEMI 
            {
              Field RESULT = null;
		ConstExpr name = (ConstExpr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		Expr exp = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Field(name.getLineNum(),
                                  name.getConstant(), exp ); 
              CUP$Parser$result = new java_cup.runtime.Symbol(5/*field*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // member ::= stmt 
            {
              Member RESULT = null;
		Stmt m = (Stmt)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = m; 
              CUP$Parser$result = new java_cup.runtime.Symbol(4/*member*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // member ::= field 
            {
              Member RESULT = null;
		Field f = (Field)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = f; 
              CUP$Parser$result = new java_cup.runtime.Symbol(4/*member*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // member_list ::= 
            {
              MemberList RESULT = null;
		 RESULT = new MemberList(getCurrLineNum()); 
              CUP$Parser$result = new java_cup.runtime.Symbol(3/*member_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // member_list ::= member_list member 
            {
              MemberList RESULT = null;
		MemberList ml = (MemberList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		Member m = (Member)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = (MemberList)ml.addElement(m); 
              CUP$Parser$result = new java_cup.runtime.Symbol(3/*member_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // member_list ::= member 
            {
              MemberList RESULT = null;
		Member m = (Member)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = (MemberList)(new MemberList(m.getLineNum()).addElement(m)); 
              CUP$Parser$result = new java_cup.runtime.Symbol(3/*member_list*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // score ::= SCORE STRING_CONST LBRACE member_list RBRACE 
            {
              Score RESULT = null;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		Token name = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		MemberList ml = (MemberList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Score(t.getLineNum(), getCurrFilename(),
                   name.getAttribute(), ml, null); 
              CUP$Parser$result = new java_cup.runtime.Symbol(2/*score*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // score ::= SCORE STRING_CONST BREAK expr LBRACE member_list RBRACE 
            {
              Score RESULT = null;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		Token name = (Token)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		Expr c = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		MemberList ml = (MemberList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Score(t.getLineNum(), getCurrFilename(),
                   name.getAttribute(), ml, c); 
              CUP$Parser$result = new java_cup.runtime.Symbol(2/*score*/, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT = null;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = new java_cup.runtime.Symbol(0/*$START*/, RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= score 
            {
              Program RESULT = null;
		Score sc = (Score)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-0)).value;
		 RESULT = new Program(0, sc); 
              CUP$Parser$result = new java_cup.runtime.Symbol(1/*program*/, RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

