
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Feb 11 16:58:42 EST 2017
//----------------------------------------------------

package bantam.parser;

/** CUP generated class containing symbol constants. */
public class TokenIds {
  /* terminals */
  public static final int LOOP = 16;
  public static final int SEMI = 36;
  public static final int LPAREN = 30;
  public static final int INSTRUMENT = 29;
  public static final int OCTAVE = 28;
  public static final int VOLUME = 8;
  public static final int MINUS = 14;
  public static final int RPAREN = 31;
  public static final int COMMA = 37;
  public static final int SCORE = 3;
  public static final int PLUS = 13;
  public static final int ASSIGN = 27;
  public static final int LSQBRACE = 34;
  public static final int ID = 39;
  public static final int EOF = 0;
  public static final int INT_CONST = 40;
  public static final int error = 1;
  public static final int BREAK = 9;
  public static final int LEX_ERROR = 2;
  public static final int LBRACE = 32;
  public static final int RBRACE = 33;
  public static final int RSQBRACE = 35;
  public static final int STRING_CONST = 42;
  public static final int COLON = 25;
  public static final int NOTE = 24;
}

