
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Apr 27 23:25:04 EDT 2017
//----------------------------------------------------

package bantam.parser;

/** CUP generated class containing symbol constants. */
public class TokenIds {
  /* terminals */
  public static final int STRING_CONST = 23;
  public static final int PLUS = 8;
  public static final int RBRACE = 14;
  public static final int OCTAVE = 7;
  public static final int RPAREN = 12;
  public static final int SEMI = 19;
  public static final int LOOP = 4;
  public static final int INSTRUMENT = 5;
  public static final int VOLUME = 6;
  public static final int SCORE = 3;
  public static final int LPAREN = 11;
  public static final int LBRACE = 13;
  public static final int ID = 21;
  public static final int NOTE = 24;
  public static final int INT_CONST = 22;
  public static final int COMMA = 20;
  public static final int RBREAK = 18;
  public static final int EOF = 0;
  public static final int LSQBRACE = 15;
  public static final int RSQBRACE = 16;
  public static final int MINUS = 9;
  public static final int LEX_ERROR = 2;
  public static final int error = 1;
  public static final int ASSIGN = 10;
  public static final int LBREAK = 17;
}

